require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe InquiriesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Inquiry. As you add validations to Inquiry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: "Philip", email: "hi@example.com", comment: "stuff" }
  }

  let(:invalid_attributes) {
    { email: "ss" }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InquiriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #new" do
    it "assigns a new inquiry as @inquiry" do
      get :new, {}, valid_session
      expect(assigns(:inquiry)).to be_a_new(Inquiry)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Inquiry" do
        expect {
          post :create, {:inquiry => valid_attributes}, valid_session
        }.to change(Inquiry, :count).by(1)
        expect(assigns(:inquiry)).to be_a(Inquiry)
        expect(assigns(:inquiry)).to be_persisted
        expect(response).to render_template(:create)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved inquiry as @inquiry" do
        post :create, {:inquiry => invalid_attributes}, valid_session
        expect(assigns(:inquiry)).to be_a_new(Inquiry)
        expect(response).to render_template("new")
      end
    end
  end
end
